spring:
  datasource:
    url: jdbc:mysql://mysql.mysql:3306/farmfarm_user_server_dev
    username: farmfarm-dev
    password: farmfarm-dev
  sql:
    init:
      mode: never
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://auth.dev.memocode.dev"

logging:
  level:
    org.springframework.security: trace

decorator:
  datasource:
    p6spy:
      enable-logging: true

custom:
  front:
    domain: "http://localhost:5173"
  api:
    domain: "https://api.dev.farmfarm.me"
  auth:
    domain: "https://auth.dev.farmfarm.me"
    client-id: "8ff2570b-8d6f-4bd9-b342-4b17e5f14d1b"
    client-secret: "2d4283d2-e8f1-41a6-bef2-a1219826b180"