# application.yml을 수정하지 마세요.
server:
  port: 9003

spring:
  profiles:
    active: local

  ########## JPA ##########
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "SECRET"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  sql:
    init:
      mode: never

  ########## SECURITY ##########
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "SECRET"

########## CUSTOM ##########
custom:
  front:
    domain: "SECRET"
    domain2: "SECRET"

########## LOGGING ##########
logging:
  level:
    org.springframework.security: info

########## DECORATOR ##########
decorator:
  datasource:
    p6spy:
      enable-logging: false

########## springdoc ##########
springdoc:
  api-docs:
    path: /users/api-docs
