spring:
  datasource:
    url: jdbc:mysql://mysql.mysql:3306/memocode_user_server_prod
  sql:
    init:
      mode: never
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://auth.memocode.dev"

custom:
  front:
    domain: "https://memocode.dev"
    domain2: "https://memocode.dev"