spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:farmfarm;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create

logging:
  level:
    org.springframework.security: trace

decorator:
  datasource:
    p6spy:
      enable-logging: true