spring:
  datasource:
    url: jdbc:mysql://prod-server:32000/memocode_user_server_dev
  sql:
    init:
      mode: never
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://auth.dev.memocode.dev"

logging:
  level:
    org.springframework.security: trace

decorator:
  datasource:
    p6spy:
      enable-logging: true

custom:
  front:
    domain: "http://localhost:5173"
    domain2: "http://localhost:5173"